"""Extrato OFX fictício com datas relativas a hoje (gerado no teste)."""
from datetime import date, timedelta


def extrato(hoje: date | None = None) -> bytes:
    h = hoje or date.today()

    def d(n):
        return (h + timedelta(days=n)).strftime("%Y%m%d") + "120000[-3:BRT]"
    return f"""OFXHEADER:100
DATA:OFXSGML
VERSION:102
SECURITY:NONE
ENCODING:USASCII
CHARSET:1252
COMPRESSION:NONE
OLDFILEUID:NONE
NEWFILEUID:NONE

<OFX>
<SIGNONMSGSRSV1><SONRS><STATUS><CODE>0<SEVERITY>INFO</STATUS><DTSERVER>{d(0)}<LANGUAGE>POR</SONRS></SIGNONMSGSRSV1>
<BANKMSGSRSV1><STMTTRNRS><TRNUID>1<STATUS><CODE>0<SEVERITY>INFO</STATUS>
<STMTRS><CURDEF>BRL<BANKACCTFROM><BANKID>0001<ACCTID>12345-6<ACCTTYPE>CHECKING</BANKACCTFROM>
<BANKTRANLIST><DTSTART>{d(-5)}<DTEND>{d(2)}
<STMTTRN><TRNTYPE>CREDIT<DTPOSTED>{d(1)}<TRNAMT>1046.73<FITID>202610001<MEMO>PIX RECEBIDO CLIENTE EXEMPLO
<STMTTRN><TRNTYPE>DEBIT<DTPOSTED>{d(-1)}<TRNAMT>-135.00<FITID>202610002<MEMO>PAGTO BOLETO LEO MADEIRAS
<STMTTRN><TRNTYPE>DEBIT<DTPOSTED>{d(0)}<TRNAMT>-29.90<FITID>202610003<MEMO>TARIFA PACOTE SERVICOS
<STMTTRN><TRNTYPE>CREDIT<DTPOSTED>{d(0)}<TRNAMT>500,00<FITID>202610004<MEMO>TRANSFERENCIA ENTRE CONTAS
</BANKTRANLIST><LEDGERBAL><BALAMT>1381.83<DTASOF>{d(2)}</LEDGERBAL></STMTRS></STMTTRNRS></BANKMSGSRSV1>
</OFX>
""".encode("latin-1")
