"""estrutura inicial

Revision ID: 6c4bd1858229
Revises: 
Create Date: 2026-10-07 04:16:24.451967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c4bd1858229'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('perda_chapa_pct', sa.Float(), nullable=False),
    sa.Column('perda_fita_pct', sa.Float(), nullable=False),
    sa.Column('chapa_comprimento_mm', sa.Float(), nullable=False),
    sa.Column('chapa_largura_mm', sa.Float(), nullable=False),
    sa.Column('serra_mm', sa.Float(), nullable=False),
    sa.Column('refilo_mm', sa.Float(), nullable=False),
    sa.Column('imposto_venda_pct', sa.Float(), nullable=False),
    sa.Column('garantia_meses', sa.Integer(), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('inscricao_estadual', sa.String(length=20), nullable=True),
    sa.Column('ncm_padrao', sa.String(length=10), nullable=False),
    sa.Column('cfop_interno', sa.String(length=4), nullable=False),
    sa.Column('cfop_interestadual', sa.String(length=4), nullable=False),
    sa.Column('csosn_padrao', sa.String(length=3), nullable=False),
    sa.Column('fiscal_ambiente', sa.String(length=12), nullable=False),
    sa.Column('fiscal_token', sa.String(length=200), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('centros_trabalho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('sequencia', sa.Integer(), nullable=False),
    sa.Column('regra', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'codigo')
    )
    with op.batch_alter_table('centros_trabalho', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_centros_trabalho_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('logradouro', sa.String(length=200), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('fornecedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('prazo_dias', sa.Integer(), nullable=False),
    sa.Column('prazo_pagamento_dias', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fornecedores_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('senha_hash', sa.String(length=200), nullable=False),
    sa.Column('perfil', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('ultimo_acesso', sa.DateTime(), nullable=True),
    sa.Column('versao_sessao', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('materiais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=60), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('unidade', sa.String(length=10), nullable=False),
    sa.Column('espessura_mm', sa.Float(), nullable=True),
    sa.Column('comprimento_mm', sa.Float(), nullable=True),
    sa.Column('largura_mm', sa.Float(), nullable=True),
    sa.Column('custo_unitario', sa.Float(), nullable=False),
    sa.Column('estoque_minimo', sa.Float(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'codigo')
    )
    with op.batch_alter_table('materiais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materiais_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('pedidos_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('previsao', sa.Date(), nullable=True),
    sa.Column('observacao', sa.String(length=500), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'numero')
    )
    with op.batch_alter_table('pedidos_compra', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedidos_compra_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('projetos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('codigo', sa.String(length=40), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('origem', sa.String(length=30), nullable=False),
    sa.Column('data_entrega', sa.Date(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('valor_tabela', sa.Float(), nullable=True),
    sa.Column('valor_pedido', sa.Float(), nullable=True),
    sa.Column('valor_venda', sa.Float(), nullable=True),
    sa.Column('frete_orcado', sa.Float(), nullable=True),
    sa.Column('montagem_orcada', sa.Float(), nullable=True),
    sa.Column('condicao_pagamento', sa.String(length=120), nullable=True),
    sa.Column('parcelas_sugeridas', sa.Integer(), nullable=True),
    sa.Column('entrada_sugerida', sa.Boolean(), nullable=True),
    sa.Column('contrato_em', sa.Date(), nullable=True),
    sa.Column('liberado_em', sa.DateTime(), nullable=True),
    sa.Column('producao_concluida_em', sa.DateTime(), nullable=True),
    sa.Column('entregue_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'codigo')
    )
    with op.batch_alter_table('projetos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projetos_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('redefinicoes_senha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.Column('usado_em', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('redefinicoes_senha', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_redefinicoes_senha_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('ambientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ambientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ambientes_projeto_id'), ['projeto_id'], unique=False)

    op.create_table('chamados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('aberto_em', sa.DateTime(), nullable=False),
    sa.Column('agendado_para', sa.Date(), nullable=True),
    sa.Column('causa', sa.String(length=20), nullable=True),
    sa.Column('solucao', sa.String(length=500), nullable=True),
    sa.Column('custo', sa.Float(), nullable=False),
    sa.Column('resolvido_em', sa.DateTime(), nullable=True),
    sa.Column('em_garantia', sa.Boolean(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'numero')
    )
    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chamados_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chamados_projeto_id'), ['projeto_id'], unique=False)

    op.create_table('itens_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('recebido', sa.Float(), nullable=False),
    sa.Column('custo_unitario', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materiais.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_compra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itens_pedido', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itens_pedido_pedido_id'), ['pedido_id'], unique=False)

    op.create_table('lancamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('categoria', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=False),
    sa.Column('pago_em', sa.Date(), nullable=True),
    sa.Column('valor_pago', sa.Float(), nullable=True),
    sa.Column('projeto_id', sa.Integer(), nullable=True),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_compra.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lancamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lancamentos_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lancamentos_projeto_id'), ['projeto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lancamentos_vencimento'), ['vencimento'], unique=False)

    op.create_table('montagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('equipe', sa.String(length=200), nullable=False),
    sa.Column('endereco', sa.String(length=300), nullable=True),
    sa.Column('observacao', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('iniciada_em', sa.DateTime(), nullable=True),
    sa.Column('concluida_em', sa.DateTime(), nullable=True),
    sa.Column('recebido_por', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('montagens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_montagens_data_inicio'), ['data_inicio'], unique=False)
        batch_op.create_index(batch_op.f('ix_montagens_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_montagens_projeto_id'), ['projeto_id'], unique=False)

    op.create_table('movimentos_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('custo_unitario', sa.Float(), nullable=False),
    sa.Column('origem', sa.String(length=20), nullable=False),
    sa.Column('referencia', sa.String(length=80), nullable=True),
    sa.Column('observacao', sa.String(length=300), nullable=True),
    sa.Column('projeto_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materiais.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimentos_estoque', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimentos_estoque_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentos_estoque_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentos_estoque_projeto_id'), ['projeto_id'], unique=False)

    op.create_table('notas_fiscais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('ref', sa.String(length=60), nullable=False),
    sa.Column('ambiente', sa.String(length=12), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('serie', sa.String(length=5), nullable=True),
    sa.Column('chave', sa.String(length=60), nullable=True),
    sa.Column('url_danfe', sa.String(length=400), nullable=True),
    sa.Column('url_xml', sa.String(length=400), nullable=True),
    sa.Column('mensagem', sa.String(length=1000), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref')
    )
    with op.batch_alter_table('notas_fiscais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notas_fiscais_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notas_fiscais_projeto_id'), ['projeto_id'], unique=False)

    op.create_table('ordens_producao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('prioridade', sa.Integer(), nullable=False),
    sa.Column('data_entrega', sa.Date(), nullable=True),
    sa.Column('criada_em', sa.DateTime(), nullable=False),
    sa.Column('concluida_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'numero')
    )
    with op.batch_alter_table('ordens_producao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ordens_producao_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordens_producao_projeto_id'), ['projeto_id'], unique=False)

    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('projeto_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('baixada_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materiais.id'], ),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservas_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservas_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reservas_projeto_id'), ['projeto_id'], unique=False)

    op.create_table('itens_checklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('montagem_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('observacao', sa.String(length=300), nullable=True),
    sa.Column('conferido_por', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['montagem_id'], ['montagens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itens_checklist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itens_checklist_montagem_id'), ['montagem_id'], unique=False)

    op.create_table('modulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ambiente_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=60), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('largura_mm', sa.Float(), nullable=True),
    sa.Column('altura_mm', sa.Float(), nullable=True),
    sa.Column('profundidade_mm', sa.Float(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ambiente_id'], ['ambientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('modulos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_modulos_ambiente_id'), ['ambiente_id'], unique=False)

    op.create_table('movimentos_bancarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('fitid', sa.String(length=120), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('lancamento_id', sa.Integer(), nullable=True),
    sa.Column('ignorado', sa.Boolean(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('importado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['lancamento_id'], ['lancamentos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'fitid')
    )
    with op.batch_alter_table('movimentos_bancarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimentos_bancarios_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentos_bancarios_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('itens_modulo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modulo_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('material_codigo', sa.String(length=60), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('unidade', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materiais.id'], ),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itens_modulo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itens_modulo_modulo_id'), ['modulo_id'], unique=False)

    op.create_table('pecas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modulo_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=60), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('material_codigo', sa.String(length=60), nullable=False),
    sa.Column('comprimento_mm', sa.Float(), nullable=False),
    sa.Column('largura_mm', sa.Float(), nullable=False),
    sa.Column('espessura_mm', sa.Float(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('veio', sa.Boolean(), nullable=False),
    sa.Column('fita_c1', sa.String(length=60), nullable=True),
    sa.Column('fita_c2', sa.String(length=60), nullable=True),
    sa.Column('fita_l1', sa.String(length=60), nullable=True),
    sa.Column('fita_l2', sa.String(length=60), nullable=True),
    sa.Column('fita_codigo', sa.String(length=60), nullable=True),
    sa.Column('fita_metros', sa.Float(), nullable=True),
    sa.Column('programa_usinagem', sa.String(length=120), nullable=True),
    sa.Column('operacoes', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materiais.id'], ),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pecas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pecas_modulo_id'), ['modulo_id'], unique=False)

    op.create_table('unidades_peca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('op_id', sa.Integer(), nullable=False),
    sa.Column('peca_id', sa.Integer(), nullable=False),
    sa.Column('sequencial', sa.Integer(), nullable=False),
    sa.Column('codigo_barras', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['op_id'], ['ordens_producao.id'], ),
    sa.ForeignKeyConstraint(['peca_id'], ['pecas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unidades_peca', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unidades_peca_codigo_barras'), ['codigo_barras'], unique=True)
        batch_op.create_index(batch_op.f('ix_unidades_peca_op_id'), ['op_id'], unique=False)

    op.create_table('etapas_unidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('centro_id', sa.Integer(), nullable=False),
    sa.Column('sequencia', sa.Integer(), nullable=False),
    sa.Column('concluida_em', sa.DateTime(), nullable=True),
    sa.Column('operador', sa.String(length=100), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['centro_id'], ['centros_trabalho.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades_peca.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('etapas_unidade', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_etapas_unidade_centro_id'), ['centro_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_etapas_unidade_unidade_id'), ['unidade_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('etapas_unidade', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_etapas_unidade_unidade_id'))
        batch_op.drop_index(batch_op.f('ix_etapas_unidade_centro_id'))

    op.drop_table('etapas_unidade')
    with op.batch_alter_table('unidades_peca', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unidades_peca_op_id'))
        batch_op.drop_index(batch_op.f('ix_unidades_peca_codigo_barras'))

    op.drop_table('unidades_peca')
    with op.batch_alter_table('pecas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pecas_modulo_id'))

    op.drop_table('pecas')
    with op.batch_alter_table('itens_modulo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_modulo_modulo_id'))

    op.drop_table('itens_modulo')
    with op.batch_alter_table('movimentos_bancarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimentos_bancarios_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_movimentos_bancarios_data'))

    op.drop_table('movimentos_bancarios')
    with op.batch_alter_table('modulos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_modulos_ambiente_id'))

    op.drop_table('modulos')
    with op.batch_alter_table('itens_checklist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_checklist_montagem_id'))

    op.drop_table('itens_checklist')
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservas_projeto_id'))
        batch_op.drop_index(batch_op.f('ix_reservas_material_id'))
        batch_op.drop_index(batch_op.f('ix_reservas_empresa_id'))

    op.drop_table('reservas')
    with op.batch_alter_table('ordens_producao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ordens_producao_projeto_id'))
        batch_op.drop_index(batch_op.f('ix_ordens_producao_empresa_id'))

    op.drop_table('ordens_producao')
    with op.batch_alter_table('notas_fiscais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notas_fiscais_projeto_id'))
        batch_op.drop_index(batch_op.f('ix_notas_fiscais_empresa_id'))

    op.drop_table('notas_fiscais')
    with op.batch_alter_table('movimentos_estoque', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimentos_estoque_projeto_id'))
        batch_op.drop_index(batch_op.f('ix_movimentos_estoque_material_id'))
        batch_op.drop_index(batch_op.f('ix_movimentos_estoque_empresa_id'))

    op.drop_table('movimentos_estoque')
    with op.batch_alter_table('montagens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_montagens_projeto_id'))
        batch_op.drop_index(batch_op.f('ix_montagens_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_montagens_data_inicio'))

    op.drop_table('montagens')
    with op.batch_alter_table('lancamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lancamentos_vencimento'))
        batch_op.drop_index(batch_op.f('ix_lancamentos_projeto_id'))
        batch_op.drop_index(batch_op.f('ix_lancamentos_empresa_id'))

    op.drop_table('lancamentos')
    with op.batch_alter_table('itens_pedido', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itens_pedido_pedido_id'))

    op.drop_table('itens_pedido')
    with op.batch_alter_table('chamados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chamados_projeto_id'))
        batch_op.drop_index(batch_op.f('ix_chamados_empresa_id'))

    op.drop_table('chamados')
    with op.batch_alter_table('ambientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ambientes_projeto_id'))

    op.drop_table('ambientes')
    with op.batch_alter_table('redefinicoes_senha', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_redefinicoes_senha_usuario_id'))

    op.drop_table('redefinicoes_senha')
    with op.batch_alter_table('projetos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projetos_empresa_id'))

    op.drop_table('projetos')
    with op.batch_alter_table('pedidos_compra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedidos_compra_empresa_id'))

    op.drop_table('pedidos_compra')
    with op.batch_alter_table('materiais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materiais_empresa_id'))

    op.drop_table('materiais')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fornecedores_empresa_id'))

    op.drop_table('fornecedores')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_empresa_id'))

    op.drop_table('clientes')
    with op.batch_alter_table('centros_trabalho', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_centros_trabalho_empresa_id'))

    op.drop_table('centros_trabalho')
    op.drop_table('empresas')
    # ### end Alembic commands ###
